# -*- coding: utf-8 -*-
"""python basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSgAw0LT9XuYr6fY_AfG4bv6M0tmZxgU

**Python Basics**

Variables :
"""

x = 5
name = "Asish"
print(x)
print(name)

"""Type Casting : Conversion of one datatype to another.

Implicit type casting : Python converts the data type automatically.
"""

a = 10
b = 2.5

c = a + b
print(c)
print(type(c))

"""Explicit type casting"""

a = "10"
b = int(a)
print(b)
print(type(b))

"""User Input"""

name = input("Enter your name: ")
age = int(input("Enter age: "))
print("age is" , age)
print("Welcome", name)

"""Operators :"""

a = 10
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)

"""Conditional Statements : (if-else)"""

marks = 75

if marks >= 90:
    print("A")
elif marks >= 60:
    print("B")
else:
    print("C")

"""Loops : (For loop and while loop)"""

for i in range(1, 6):
    print(i)

i = 1
while i <= 5:
    print(i)
    i += 1

"""Strings :"""

text = "Python"

print(text.upper())
print(text.lower())
print(text[0])
print(text.replace("P", "p"))

ch = 'a'
print(ch.isalpha())
#check alphabet

"""Lists :"""

nums = [10, 20, 30]

nums.append(40)
nums.remove(20)

print(nums)

for n in nums:
    print(n)

"""Tuples"""

t = (1, 2, 3)
print(t[0])

"""Dictionary"""

student = {
    "name": "Asish",
    "age": 21,
    "branch": "CSE"
}

print(student["name"])

for key, value in student.items():
    print(key, value)

"""Functions :"""

def add(a, b):
    return a + b

print(add(5, 3))

"""OOPS BASICS"""

class Student:
    def __init__(self, name):
        self.name = name

    def show(self):
        print("Name:", self.name)

s1 = Student("Asish")
s1.show()

"""Exeption Handling"""

try:
    x = int(input("Enter number: "))
    print(10 / x)
except ZeroDivisionError:
    print("Cannot divide by zero")
except ValueError:
    print("Invalid input")

"""Sets :"""

l = [1, 2, 2, 3]
s = set(l)
print(s)

"""event traker"""

hotel = {
    "101": "Empty",
    "102": "Empty",
    "103": "Empty"
}

# Book a room
room = input("Enter room number (101, 102, 103): ")
guest = input("Enter guest name: ")

if room in hotel:
    if hotel[room] == "Empty":
        hotel[room] = guest
        print(f"Room {room} booked for {guest}")
    else:
        print(f"Room {room} is already occupied")
else:
    print("Invalid room number")

print("\nHotel Status:")
print(hotel)

# Vacate a room
out_room = input("Enter room number to vacate: ")

if out_room in hotel:
    hotel[out_room] = "Empty"
    print(f"Room {out_room} is now empty")
else:
    print("Invalid room number")

# Show final results
print("\nFinal Hotel Status:")
print(hotel)

def substract(a,b):
  print(a-b)
substract(10,20,30)



"""TRANSACTION SYSTEM USING FUNCTION :"""

balance =10000;
def deposit():
    global balance
    amount = int(input("Enter amount to deposit: "))
    if amount > 0:
        balance += amount
        print("Deposit successful!")
    else:
        print("Invalid amount")
def withdraw():
    global balance
    amount = int(input("Enter amount to withdraw: "))
    if amount <= balance and amount > 0:
        balance -= amount
        print("Withdrawal successful!")
    else:
        print("Insufficient balance or invalid amount")
def check_balance():
    print("Current Balance:", balance)
def transaction_menu():
    while True:
        print("\n--- Transaction Menu ---")

        print("1. Deposit")
        print("2. Withdraw")
        print("3. Check Balance")
        print("4. Exit")

        choice = int(input("Enter your choice: "))
        if choice == 1:
            deposit()
        elif choice == 2:
            withdraw()
        elif choice == 3:
            check_balance()
        elif choice == 4:
            print("Exiting Transaction System")
            break
        else:
            print("Invalid choice")


transaction_menu()